# One-off localization patch for index.html
from pathlib import Path

p = Path(__file__).resolve().parents[1] / "index.html"
text = p.read_text(encoding="utf-8")

# Structural
text = text.replace('<html lang="zh-CN">', '<html lang="en">')
text = text.replace("<title>小游戏 Feed</title>", "<title>Game Feed</title>")
text = text.replace(
    """      <nav class="tabs tabs-wide">
        <button class="tab active" data-tab="recommend" type="button">推荐</button>
        <button class="tab" data-tab="games" type="button">游戏</button>
        <button class="tab" data-tab="knowledge" type="button">知识</button>
        <button class="tab" data-tab="life" type="button">生活</button>
      </nav>""",
    """      <nav class="tabs tabs-wide">
        <button class="tab active" data-tab="recommend" type="button">For You</button>
        <button class="tab" data-tab="games" type="button">Games</button>
      </nav>""",
)
text = text.replace(
    """    <button class="fab" aria-label="发布">+</button>

    <nav class="bottom-nav">
      <button class="bottom-nav-item"><span class="nav-icon">↻</span><span>对话</span></button>
      <button class="bottom-nav-item active">
        <span class="nav-badge">闪应用</span>
        <span class="nav-icon">💡</span><span>灵光圈</span>
      </button>
      <button class="bottom-nav-item"><span class="nav-icon">📞</span><span>打电话</span></button>
      <button class="bottom-nav-item"><span class="nav-icon">👁</span><span>开眼</span></button>
    </nav>""",
    "",
)
text = text.replace(
    """        <p class="feed-empty-text">这里还没有内容</p>
        <p class="feed-empty-sub">换个 Tab 看看吧</p>""",
    """        <p class="feed-empty-text">Nothing here yet</p>
        <p class="feed-empty-sub">Try another tab</p>""",
)

pairs = [
    ('aria-label="搜索"', 'aria-label="Search"'),
    ('alt="头像"', 'alt="Profile"'),
    ("全屏", "Full"),
    ('aria-label="声音"', 'aria-label="Sound"'),
    # Fortune
    ("今日签文", "Daily Fortune"),
    ("点击签筒，抽取今日签文", "Tap the tube to draw today's fortune"),
    ('aria-label="点击抽签"', 'aria-label="Draw fortune"'),
    ("再抽一次", "Draw Again"),
    ("重新抽签", "Reset"),
    ("心上签小屋", "Fortune Corner"),
    ("每天给自己一点温柔", "A little kindness for yourself each day"),
    ("小满同学", "Mia"),
    # Earth
    ("蓝星日记", "Blue Planet Diary"),
    ("每日心愿 集录处", "Daily quests & wishes"),
    ("随机任务", "Random Quest"),
    ("任务记录", "Quest Log"),
    ("嘿呀！今日任务来啦，准备好接收了吗？ 🎁", "Hey! Today's quest is here — ready? 🎁"),
    ("学习一个童谣", "Learn a nursery rhyme"),
    ("已完成", "Complete"),
    ("功德+1", "Karma +1"),
    ("快乐值 +999", "Joy +999"),
    ("幸福指数爆表", "Happiness maxed out"),
    ("今日善行已记录", "Good deed logged"),
    ("宇宙为你点赞", "The universe approves"),
    ("温暖已送达", "Warmth delivered"),
    ("返回地球", "Back to Earth"),
    ('aria-label="关闭"', 'aria-label="Close"'),
    ("还没有完成过任务哦", "No completed quests yet"),
    ("蓝星日记·每日任务站", "Blue Planet · Daily Quests"),
    ("完成小目标，积攒好心情", "Small wins, better mood"),
    ("04月20日", "Apr 20"),
    ("晚舟", "Nova"),
    # Chick
    ('aria-label="摸摸小鸡"', 'aria-label="Pet the chick"'),
    ("软啾解压屋", "Squishy Chick"),
    ("按一按，烦恼就溜走", "Squeeze away the stress"),
    ("开始解压", "Start"),
    ("成就徽章", "Achievements"),
    ("← 返回", "← Back"),
    ("← 返回游戏", "← Back to Game"),
    ("解压值", "Relief"),
    ("点击次数", "Taps"),
    ("重置", "Reset"),
    ('aria-label="挤压小鸡"', 'aria-label="Squish chick"'),
    ("橡皮小鸡", "Rubber"),
    ("气球小鸡", "Balloon"),
    ("泥胶小鸡", "Clay"),
    ("解压达人", "Relief Pro"),
    ("累计解压值达到100", "Reach 100 relief points"),
    ("点击狂魔", "Tap Master"),
    ("点击50次", "Tap 50 times"),
    ("气球爆炸", "Pop!"),
    ("让气球小鸡爆炸", "Pop the balloon chick"),
    ("当前解压值", "Relief"),
    ("总点击次数", "Total taps"),
    ("林间小筑", "Forest Nest"),
    # Block
    ("萌块堆堆", "Cute Stack"),
    ("开始挑战", "Start"),
    ("成绩记录", "Scores"),
    ("得分", "Score"),
    ("记录", "Log"),
    ('aria-label="游戏区域"', 'aria-label="Game area"'),
    ('aria-label="旋转"', 'aria-label="Rotate"'),
    ('aria-label="左"', 'aria-label="Left"'),
    ('aria-label="下"', 'aria-label="Down"'),
    ('aria-label="右"', 'aria-label="Right"'),
    ('title="清除底行"', 'title="Clear bottom row"'),
    ('title="加速"', 'title="Speed up"'),
    ('title="重来"', 'title="Restart"'),
    ("游戏结束 · 点击重来", "Game Over · Tap to retry"),
    ("还没有挑战记录哦", "No scores yet"),
    ("萌块堆堆·森系版", "Cute Stack · Forest"),
    ("把可爱木块堆整齐，挑战更高得分", "Stack blocks clean, chase high scores"),
    ("像素小鹿", "Pixel Deer"),
    # Shop
    ("全日", "OPEN"),
    ("鲜果驿站", "Fresh Fruit Stand"),
    ("从巷口小店到人气铺子", "From corner stall to crowd favorite"),
    ("开门营业", "Open Shop"),
    ("收<br>银<br>台", "C<br>A<br>S<br>H"),
    ("点击商品放置到货架", "Tap items to stock shelves"),
    ("← 打烊", "← Close"),
    ("小店指南", "Shop Guide"),
    ("点底部商品，再点空货架补货", "Tap goods, then empty shelf to restock"),
    ("等候客人自行选购", "Wait for customers to browse"),
    ("客人到收银台后，点一下收款", "Tap checkout when they reach the counter"),
    ("每轮 60 秒，尽量多赚营业额", "60 seconds per round — maximize sales"),
    ("明白啦！", "Got it!"),
    ("本轮收工", "Round Complete"),
    ("营业额", "Revenue"),
    ("成交", "Orders"),
    ("单", " orders"),
    ("口碑", "Rating"),
    ("再开一轮", "Another Round"),
    ("返回首页", "Home"),
    ("鲜果驿站·经营小记", "Fresh Fruit Stand · Tycoon"),
    ("当一回掌柜，把货架摆满、客人迎进门", "Stock shelves and welcome customers"),
    ("木木掌柜", "Woody"),
    # Leap
    ("连跳挑战", "Combo Jump"),
    ("荷芽蹦蹦", "Lily Pad Leap"),
    ("下水玩玩", "Jump In"),
    ("存档", "Save"),
    ("连跳", "Combo"),
    ("荷币", "Coins"),
    ("微雨 5分", "Drizzle 5m"),
    ("薄暮 7分", "Dusk 7m"),
    ('aria-label="荷塘跳跃"', 'aria-label="Pond jump"'),
    ("长按蓄力，跃向亮叶｜连跳越高分越多", "Hold to charge · land on bright pads · chain combos"),
    ("← 上岸", "← Exit"),
    ("浮岛小铺", "Floating Shop"),
    ("双击右下角浮岛可打开", "Double-tap island (bottom-right) to open"),
    ("关闭", "Close"),
    ("荷芽蹦蹦·水塘篇", "Lily Pad Leap · Pond"),
    ("长按蓄力跃荷叶，收集荷币装扮你的小蛙", "Charge, hop pads, collect coins for your frog"),
    ("塘边造梦", "Pond Dreamer"),
    # Run
    ("流光疾跑", "Neon Rush"),
    ("▶ 出发冲刺", "▶ Start Run"),
    ("光币", "Coins"),
    ('aria-label="霓虹跑酷"', 'aria-label="Neon runner"'),
    ("← → 切道　↑ 跳跃　↓ 滑铲", "← → lane · ↑ jump · ↓ slide"),
    ("← 退出", "← Exit"),
    ("冲刺结束", "Run Over"),
    ("距离", "Distance"),
    ("再来一次", "Try Again"),
    ("流光疾跑·霓虹篇", "Neon Rush · Cyber"),
    ("三条光道狂奔，闪避障碍拾取光币", "Three lanes, dodge, collect coins"),
    ("赛博小K", "Cyber K"),
    # Face
    ("#反差挑战", "#GlowUp"),
    ("一秒超模变脸", "Runway Glow-Up"),
    ("摆烂素人 → 秀场女王，跟 beat 一键切换", "Couch mode → runway queen on the beat"),
    ("开始整活", "Start"),
    ("🥁 卡第4拍", "🥁 Hit beat 4"),
    ("⚡ 5轮通关", "⚡ 5 rounds"),
    ("📸 可反复拍", "📸 Replay anytime"),
    ("摆烂 mode", "Couch mode"),
    ('aria-label="变脸展示"', 'aria-label="Face transform"'),
    ("预备…跟着 beat 走", "Get ready… follow the beat"),
    ("拍!", "Go!"),
    ("← 退出", "← Exit"),
    ("杀疯了！！", "SLAYED!!"),
    ("5 轮超模变身完成", "5 runway transforms complete"),
    ("发给闺蜜：看我一秒换头", "Send to friends: watch the glow-up"),
    ("再来一轮", "Play Again"),
    ("节奏偏了一点点", "Slightly off beat"),
    ("再听一遍 beat 试试", "Listen again and retry"),
    ("重新挑战", "Retry"),
    ("一秒超模变脸", "Runway Glow-Up"),
    ("摆烂素人秒变秀场女王，反差整活必玩", "Instant couch-to-runway transformation"),
    ("反差工作室", "Contrast Studio"),
    # Box
    ("#猎奇解压", "#FlavorGuess"),
    ("口味盲盒猜猜猜", "Mystery Flavor Box"),
    ("饮品零食网红口味，开盒猜口感", "Guess wild drink & snack flavors"),
    ("已开", "Opened"),
    ("盒，猜口感！", " boxes — guess the taste!"),
    ("开一盒", "Open One"),
    ("这盒更像？", "This box feels…"),
    ("#玩梗造句", "#MemeLines"),
    ("天生 VS 被迫", "Born To vs Forced To"),
    ("随机来一句", "Random Line"),
    ("天生喜欢", "Born to love "),
    ("，被迫", ", forced to "),
    ("自助造句", "Build Line"),
    ("喜欢什么", "Love what"),
    ("被迫做什么", "Forced to do"),
    ("生成！", "Generate!"),
    ("#萌宠模仿", "#PetOffice"),
    ("萌宠打工秀", "Office Pets"),
    ("它们有情绪，你也有——学它们摸鱼打工", "Pets with feelings — copy their WFH vibes"),
    ("● 工位 LIVE", "● OFFICE LIVE"),
    ("等待切换…", "Waiting…"),
    ("点击切换下一个打工人", "Tap to switch scene"),
    ("🎭 模仿一下", "🎭 Copy Pose"),
    ("🐾 切换场景", "🐾 Switch Scene"),
    ("已解锁", "Unlocked"),
    ("个场景", " scenes"),
    ("萌宠打工模仿秀", "Office Pet Impressions"),
    ("修勾上班猫咪摸鱼，看着模仿超治愈", "Dogs grind, cats slack — oddly healing"),
    ("毛孩工位", "Fur Desk"),
    ("#云打卡", "#TravelCheckIn"),
    ("彩虹盐湖", "Rainbow Salt Lake"),
    ("不用出门，也能拍出旅行大片", "Travel vibes without leaving home"),
    ("点击切换打卡文案", "Tap to switch caption"),
    ("📸 打卡成功", "📸 Checked in!"),
    ("已存入旅行相册", "Saved to travel album"),
    ("🌈 换打卡场景", "🌈 Switch Scene"),
    ("📸 拍照打卡", "📸 Snap & Check In"),
    ("已打卡", "Checked in"),
    ("次 · 云旅人认证", " times · Cloud Traveler"),
    ("加州彩虹盐湖打卡", "Rainbow Salt Lake Check-in"),
    ("脑补网红机位，沉浸式云旅游", "Iconic spots, immersive cloud travel"),
    ("云旅人", "Cloud Traveler"),
    ("#摸牌解压", "#TileZen"),
    ("趣味摸牌", "Tile Draw"),
    ("摸一张", "Draw Tile"),
    ("已摸", "Drawn"),
    ("张", " tiles"),
    ("单人麻将摸牌", "Solo Tile Draw"),
    ("碎片化时间随手摸牌，解压又上头", "Quick tile draws for chill breaks"),
    ("牌友小筑", "Tile House"),
    ("星落拾光·夜空篇", "Starfall · Night Sky"),
    ("左右移动光篮，接住坠落的星星", "Move the basket, catch falling stars"),
    ("叠层手速台", "Stack Rush"),
    ("节奏落块，叠得越高分越多", "Drop blocks on beat — stack higher"),
    ("配对翻翻乐", "Memory Match"),
    ("考验记忆力，找出所有相同图案", "Find all matching pairs"),
    ("数字合并格", "Number Merge"),
    ("经典数字益智，合并到更大", "Classic merge puzzle — go bigger"),
    ("节拍点点·光轨篇", "Beat Tap · Light Rails"),
    ("四轨节奏，精准点击拿高分", "Four lanes — tap on beat for high scores"),
    ("开始", "Start"),
    ("得分", "Score"),
    ("最高", "Best"),
    ("配对", "Pairs"),
    ("步数", "Moves"),
    ("连击", "Combo"),
    ("完美", "Perfect"),
    ("Good", "Good"),
    ("Miss", "Miss"),
]

for old, new in pairs:
    text = text.replace(old, new)

p.write_text(text, encoding="utf-8")
print("index.html localized:", len(pairs), "replacements")
